#ifndef PROTOCOL_H
#define PROTOCOL_H
enum MSGTYPE{
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILED_ACCOUNT_OR_PASSWD,
    LOGIN_FAILED_NOT_REGIST,
    REGIST_REQUEST,
    REGIST_SUCCESS,
    REGIST_FAILED,
    REGIST_CODE_NOT_RIGHT,
    REQUEST_CODE,
    RESPONSE_CODE_OK,
    RESPONSE_CODE_ISEXIST,
    CODE_NONCONRECT
};
#endif // PROTOCOL_H
